# Set site variables
title = "Your Short Article Title"
baseURL = "/"
relativeURLs = true
github = "https://github.com/danielroelfs/manuscript-site-template"

# Mandatory settings
languageCode = "en-us"
theme = "dimension"
publishDir = "docs"
staticDir = ["files"]

# Set other variables
[params]
  pubtitle = "The awesome, clever, professional title of your publication"
  authors = "You, John Doe, Jane Doe, another colleague, that one person who did nothing, that person the PI made you add, and your boss"
  icon = "brain"
  email = "daniel.roelfs@medisin.uio.no"
  github = "https://github.com/danielroelfs"
  twitter = "https://twitter.com/dthroelfs"
  paper = "https://www.journals.elsevier.com/neuroimage/"
  preprint = "https://www.biorxiv.org"
  dark = false
  background = "images/bg_light.jpg"

# Menu links
[[menu.main]]
    name = "Paper + Preprint"
    url  = "paper-and-preprint"
    weight = 1
[[menu.main]]
    name = "Summary"
    url = "summary"    
    weight = 2
[[menu.main]]
    name = "Data"
    url = "data"
    weight = 3
[[menu.main]]
    name = "Code"
    url = "code"
    weight = 4
[[menu.main]]
    name = "About"
    url = "about"
    weight = 5
